version: '3.8'

services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  nxginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - api # todo: might not be necessary
    volumes:
      - /client/node_modules
      - ./client:/app
